#mirrors meta.yaml but can be used to build a conda enviroment WITHOUT pima for debugging
name: base

channels:
  - bioconda
  - conda-forge

dependencies:
    - git==2.39.1
    - gawk==5.3
    - bedtools==2.31.1
    - biopython==1.84
    - blast==2.16
    - bwa==0.7.18
    - curl
    - flye==2.9.4
    - raven-assembler==1.8.3
    - mdutils==1.6.0
    - minimap2==2.28
    - multiprocess=0.70.16
    - mummer==3.23
    - kraken2==2.1.3
    - spades==4.0.0
    - pandas==2.2.2
    - pandoc==3.3
    - weasyprint==62.3 # pdf engine for pandoc
    - pango==1.50.14
    - pathos
    - python >=3.9,<3.11 #,<3.9
    - pyfaidx==0.8.1.2
    - python_circos ## will replace with the development verison using pip in pima_install.sh script
    - r
    - r-hash #needed for pChunks
    - r-stringr #needed for pChunks
    - r-gridextra #needed for pChunks
    - r-optparse #needed for pChunks
    - samtools==1.18 #needs to be the conda-forge version and NOT the bioconda version
    - varscan==2.4.6
    - medaka >=1.11 #bumped to get access to the inspect model tools
    - pilon==1.24
    - polypolish==0.6
    - quast==5.2.0 #installs perl-circos as a dependency...
    - nextflow==24.04.4 # used for parallelizing multiplex runs
